#!/usr/bin/env bash
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PARTIALS="$REPO/src/partials"
OUT="$REPO/index.html"

{
cat << 'HTML'
<!DOCTYPE html>
<!-- Generated by src/build.sh — edit src/ partials, not this file directly -->
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>ARES</title>
  <link rel="icon" type="image/png" sizes="64x64" href="assets/favicon.png" />
  <link rel="stylesheet" href="src/styles/main.css" />
</head>
<body>
HTML

cat "$PARTIALS/nav.html"
cat "$PARTIALS/intro.html"
echo ''
echo '<section id="projects">'
cat "$PARTIALS/talos.html"
echo ''
cat "$PARTIALS/icarus.html"
echo ''
cat "$PARTIALS/upcoming.html"
echo '</section>'
echo ''
cat "$PARTIALS/scripts.html"

cat << 'HTML'
</body>
</html>
HTML

} > "$OUT"

echo "✓  Built index.html"
